# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d6b3ac4cceaa574f7599aeb5c6f7a7f04bf1dbf0b328f784178f83cf9c20c6ba0371563b4b6babd13cc8ac14d85705422ce705bd9f8d46c9bb2bcf2e0a3e1c0

test:
  secret_key_base: 1e02313b01c432c9115a9bcf9ed8ece263bdfd838d28de8f98bbc4c62aa0dd3dc5065de7c678053300f5abffeec5da8fe5ae189480b19925e383531ada7e4d2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
